name: ficc-m1
channels:
  - apple
  - conda-forge
dependencies:
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - pip=22.1
  - python=3.9.7
  - python_abi=3.9=2_cp39
  - tensorboard=2.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow-deps=2.8.0
  - numpy=1.21.2
  - libpng
  - "libblas=*=*accelerate"
  - pip:
    - captum==0.4.1
    # - dask==2021.12.0
    # - dask-bigquery==2022.5.0
    - gcsfs==2022.2.0
    - google-api-core==2.7.1
    - google-cloud==0.34.0
    - google-cloud-bigquery==2.31.0
    - google-cloud-bigquery-storage==2.13.1
    - google-cloud-core==2.2.1
    - google-cloud-dataflow-client==0.4.1
    - google-cloud-storage==2.1.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.1.0
    - googleapis-common-protos==1.54.0
    # - grpcio-status==1.42.0
    # - ipykernel==6.6.0
    # - ipython==7.30.1
    # - ipython-genutils==0.2.0
    # - ipywidgets==7.6.5
    # - itsdangerous==2.1.0
    # - jedi==0.18.1
    # - jinja2==3.0.3
    # - jmespath==0.10.0
    # - joblib==1.1.0
    # - jsonlines==3.0.0
    # - jsonschema==4.2.1
    # - jupyter==1.0.0
    # - jupyter-client==7.1.0
    # - jupyter-console==6.4.0
    # - jupyter-core==4.9.1
    # - jupyterlab-pygments==0.1.2
    # - jupyterlab-widgets==1.0.2
    # - keras==2.2.5
    # - keras-applications==1.0.8
    - keras-tuner==1.1.0
    # - kiwisolver==1.3.2
    # - kt-legacy==1.0.4
    # - libclang==12.0.0
    # - lightgbm==3.3.1
    # - locket==0.2.1
    # - markupsafe==2.0.1
    # - matplotlib==3.5.1
    # - matplotlib-inline==0.1.3
    # - mistune==0.8.4
    # - mpmath==1.2.1
    # - nbclient==0.5.9
    # - nbconvert==6.3.0
    # - nbdiff==1.0.3
    # - nbformat==5.1.3
    # - nest-asyncio==1.5.4
    # - networkx==2.6.3
    # - notebook==6.4.6
    # - numpy==1.21.5
    # - packaging==21.3
    - pandarallel==1.5.4
    - pandas==1.3.4
    # - pandocfilters==1.5.0
    # - parso==0.8.3
    # - partd==1.2.0
    # - pathtools==0.1.2
    # - pexpect==4.8.0
    - pickle5==0.0.11
    # - pickleshare==0.7.5
    # - pillow==8.4.0
    # - prometheus-client==0.12.0
    # - promise==2.3
    # - prompt-toolkit==3.0.24
    # - proto-plus==1.19.8
    # - psutil==5.8.0
    # - ptyprocess==0.7.0
    # - py4j==0.10.9.3
    - pyarrow==6.0.1
    # - pycodestyle==2.8.0
    # - pydantic==1.9.0
    # - pydeprecate==0.3.1
    # - pydot==1.4.2
    # - pygments==2.10.0
    # - pygraphviz==1.7
    # - pyparsing==3.0.6
    # - pyrsistent==0.18.0
    # - pyspark==3.2.1
    # - pysr==0.6.14
    # - python-dateutil==2.8.2
    # - python-graphviz==0.19
    # - python-levenshtein==0.12.2
    - pytorch-lightning==1.5.10
    # - pytz==2021.3
    # - pyyaml==6.0
    # - pyzmq==22.3.0
    # - qtconsole==5.2.1
    # - qtpy==1.11.3
    # - s3transfer==0.5.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    # - send2trash==1.8.0
    # - sentry-sdk==1.5.0
    # - setuptools==59.5.0
    # - shortuuid==1.0.8
    # - single-source==0.1.5
    # - smmap==5.0.0
    # - spektral==0.0.13
    # - subprocess32==3.5.4
    # - sympy==1.9
    - tensorflow-estimator==2.8.0
    - tensorflow-macos==2.8.0
    - tensorflow-metal
    # - terality==0.14.1
    # - terminado==0.12.1
    # - testpath==0.5.0
    # - threadpoolctl==3.0.0
    # - toml==0.10.2
    # - toolz==0.11.2
    - torch==1.10.2
    - torchmetrics==0.7.2
    - torchvision==0.11.3
    # - tornado==6.1
    - tqdm==4.62.3
    # - traitlets==5.1.1
    - wandb==0.12.10
    # - wcwidth==0.2.5
    # - webencodings==0.5.1
    # - widgetsnbextension==3.5.2
    # - yaspin==2.1.0
    - .
